#!/bin/bash

# Extract values using jq
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')  # Capitalize first letter
height=$(jq '.height' data.json | awk '{ print $1 / 10 }') # decimeters to meters
weight=$(jq '.weight' data.json | awk '{ print $1 / 10 }') # hectograms to kilograms
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')  # Capitalize

# Format and print
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."

